//
//  SwiftUIView.swift
//  NYT The Mini
//
//  Created by Sanjana G on 4/22/24.
//

import SwiftUI

struct ListView: View {
    var body: some View {
        NavigationView{
            VStack{
                ScrollView{
                    ZStack{
                        Rectangle()
                            .foregroundColor(Color("lightBlue"))
                            .frame(width: 390, height: 40)
                        HStack{
                            Text("ACROSS")
                                .bold()
                            Spacer()
                            Text("tap to switch direction")
                                .italic()
                        }
                        .padding()
                    }
                    HStack{
                        Text("1")
                            .bold()
                        Text("Bluegrass instrument")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("2")
                            .bold()
                        Text("Audible way to think")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("3")
                            .bold()
                        Text("Aladdin character whose first line is \"Oy! 10,000 years will give you such a crick in the neck!\"")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("4")
                            .bold()
                        Text("Across: Members of a company's C-suite")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("5")
                            .bold()
                        Text("Behind schedule")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    ZStack{
                        Rectangle()
                            .foregroundColor(Color("lightBlue"))
                            .frame(width: 390, height: 40)
                        HStack{
                            Text("DOWN")
                                .bold()
                            Spacer()
                            Text("tap to switch direction")
                                .italic()
                        }
                        .padding()
                    }
                    HStack{
                        Text("1")
                            .bold()
                        Text("The schmear goes here")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("2")
                            .bold()
                        Text("Amazon's assistant")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("3")
                            .bold()
                        Text("Group of nine")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("4")
                            .bold()
                        Text("Battery life, informally")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    Divider()
                    HStack{
                        Text("5")
                            .bold()
                        Text("Poems like \"To Autumn\" and \"To a Skylark\"")
                        Spacer()
                    }
                    .padding(.horizontal, 10)
                    HStack{
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(Color.black)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Rectangle()
                            .foregroundColor(.white)
                            .border(/*@START_MENU_TOKEN@*/Color.black/*@END_MENU_TOKEN@*/)
                            .frame(width: 30, height: 30)
                        Spacer()
                    }
                    .padding()
                    
                }
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}

#Preview {
    ListView()
}
